[tools]
go = "1.25.6"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/bootdotdev/bootdev" = "latest"
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"